### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by theJenix** [haxe-react/semantic-ui-react#5]
I just installed this, and when I went to build my project it gave me the following error:
"Error: Error: Cannot process [semantic-ui-react,git,git@github.com,haxe-react/semantic-ui-react.git]: Library tink_hxx is not installed : run 'haxelib install tink_hxx'"

Should tink_hxx be listed in the haxelib.json file as a dependency?

**Comment by kevinresol** [comment]
I don't think so, this library contains only externs and shouldn't need hxx (unless its dependencies do)

**Comment by theJenix** [comment]
It looks like it's required by react-next.  I'm not really sure how dependency resolution works here, but I can confirm I did have to manually install tink_hxx after installing this project in order for my build to work.

**Comment by kevinresol** [comment]
react-next does specify tink_hxx as its dependency.

https://github.com/kLabz/haxe-react/blob/19f5469d3aa0662f1bf056741987f166492cd8a9/haxelib.json#L14

so I guess something is wrong at somewhere, perhaps haxelib itself.

I recommend using [lix](https://github.com/lix-pm/lix.client)
